### ISSUE TITLE
Submitted PDF in a release

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/ship-of-theses#2]
Hi @aimalz 

Very well done on completing your thesis work, I'm really looking forward to your defense. Can I suggest that you make a PDF of the submitted version, check it in, and then make a GitHub release for this version? That way we avid readers can download the manuscript with ease, and you will be able to track changes since submission. I'm not sure how post-defense corrections will work, but if you think the final final version is still to come, you could make the "Submitted" version a "pre-release".

Congratulations again!

Phil

**Comment by aimalz** [comment]
Hi @drphilmarshall there is now a [release](https://github.com/aimalz/ship-of-theses/releases/tag/v1.0-beta)!  Technically this is the final version, but I've started getting feedback from my readers so marked it as a "beta" because I'll be updating it before [drawing attention to it online](https://zenodo.org/communities/astrothesis).

**Comment by drphilmarshall** [comment]
Great, thank you! Am enjoying reading the PDF :-)

>
